#!/bin/sh

for volatile in $D/etc/default/volatiles/*; do
    if [ ! -e "$volatile" ]; then
        continue
    fi

    outfile="$D/usr/lib/tmpfiles.d/${volatile##*/}.conf"
    echo >&2 "update-tmpfiles: Processing $volatile"
    echo >&2 "update-tmpfiles: Writing converted file to $outfile"

    mkdir -p $D/usr/lib/tmpfiles.d
    grep -v "^#" "$volatile" | \
        while read type user group mode path linksource; do
            case "$type" in
                l)
                    type=L
                    ;;
                f)
                    type=F
                    ;;
                "")
                    continue
                    ;;
            esac

            if [ "$linksource" = "none" ]; then
                linksource=-
            fi

            echo "$type $path $mode $user $group - $linksource"
        done >$outfile
    rm -f "$volatile"
done
exit 0
