#!/bin/sh
#
# Perform a bind mount, copying existing files as we do so to ensure the
# overlaid path has the necessary content.

if [ $# -lt 2 ]; then
    echo >&2 "Usage: $0 SOURCE DEST [OPTIONS]"
    exit 1
fi

source=$1
dest=$2

if [ $# -gt 2 ]; then
    options=$3
else
    options=
fi

[ -n "$options" ] && options=",$options"

mkdir -p "${source%/*}"
if [ -d "$dest" ]; then
    if [ ! -d "$source" ]; then
        mkdir "$source"
        cp -pPR "$dest"/. "$source/"
    fi
elif [ -f "$dest" ]; then
    if [ ! -f "$source" ]; then
        touch "$source"
    fi
fi

mount -o "bind$options" "$source" "$dest"
