#!/bin/sh

if [ ! -e /etc/bindpaths ]; then
    echo >&2 "Error: /etc/bindpaths does not exist"
    exit 1
fi

ret=0
for path in $(cat /etc/bindpaths); do
    ls $path/ | sort | while read config; do
        config="$path/$config"
        [ -e "$config" ] || continue

        cat "$config" | while read source dest options; do
            bind-mount-copy "$source" "$dest" "$options" || ret=$?
        done
    done
done
exit $ret
